list.h: Make list_append static
When compiling -g -O0 we get a linker error:

/usr/bin/ld: ledctl-ledctl.o: in function `_ibpi_state_init':
ledmon/src/ledctl/ledctl.c:318: undefined reference to `list_append'

Corrected with making this inline function static which is described:
http://gcc.gnu.org/onlinedocs/gcc/Inline.html

Signed-off-by: Tony Asleson <tasleson@redhat.com>